# Generated by Django 2.2.1 on 2019-05-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='click',
            field=models.IntegerField(blank=True, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='content',
            field=models.CharField(blank=True, max_length=500, verbose_name='物品详情'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=200, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='invertory',
            field=models.IntegerField(blank=True, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='last_date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='goods', verbose_name='物品图片'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='title',
            field=models.CharField(max_length=20, verbose_name='物品名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TypeInfo', verbose_name='物品类型'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='typeinfo',
            name='title',
            field=models.CharField(max_length=20, verbose_name='类型名称'),
        ),
    ]
